//! LLM Integration: Phi-2 and OSS Model Support
//!
//! Interfaces with open-source LLMs for explanation generation.
//! Supports: Phi-2 (3.8B, MIT), Mistral 7B, other GGML models.
//!
//! NOTE: In production, uses llama.cpp or similar inference engine.
//! For testing, provides template-based fallback.

use serde::{Deserialize, Serialize};

/// LLM-generated explanation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LLMExplanation {
    /// The generated explanation
    pub text: String,

    /// Confidence in explanation (0.0-1.0)
    pub confidence: f32,

    /// Which LLM generated this
    pub model: String,

    /// Inference time (milliseconds)
    pub inference_time_ms: f32,

    /// Whether this came from LLM or fallback
    pub is_from_llm: bool,
}

/// Configuration for LLM inference
#[derive(Debug, Clone)]
pub struct LLMConfig {
    /// Model name (phi-2, mistral-7b, etc.)
    pub model_name: String,

    /// Model size (in billions of parameters)
    pub model_size_b: f32,

    /// Inference backend (llama.cpp, ollama, etc.)
    pub backend: InferenceBackend,

    /// Context window size (tokens)
    pub context_window: usize,

    /// Max tokens to generate
    pub max_tokens: usize,

    /// Temperature (creativity 0.0-1.0)
    pub temperature: f32,

    /// Whether to use LLM or fallback only
    pub enabled: bool,
}

/// Supported inference backends
#[derive(Debug, Clone, PartialEq)]
pub enum InferenceBackend {
    LlamaCpp,      // llama.cpp (local inference)
    Ollama,        // Ollama (local)
    Huggingface,   // Hugging Face Inference API
    LocalPython,   // Direct Python integration
    Fallback,      // Template-based (no LLM)
}

impl std::fmt::Display for InferenceBackend {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            InferenceBackend::LlamaCpp => write!(f, "llama.cpp"),
            InferenceBackend::Ollama => write!(f, "Ollama"),
            InferenceBackend::Huggingface => write!(f, "Hugging Face"),
            InferenceBackend::LocalPython => write!(f, "Local Python"),
            InferenceBackend::Fallback => write!(f, "Fallback"),
        }
    }
}

/// LLM-based explainer for robot incidents
pub struct LLMExplainer {
    config: LLMConfig,
    prompt_cache: std::collections::HashMap<String, String>,
}

impl LLMExplainer {
    /// Create new LLM explainer
    pub fn new(config: LLMConfig) -> Self {
        LLMExplainer {
            config,
            prompt_cache: std::collections::HashMap::new(),
        }
    }

    /// Create with defaults (fallback mode)
    pub fn new_fallback() -> Self {
        LLMExplainer {
            config: LLMConfig {
                model_name: "phi-2".to_string(),
                model_size_b: 3.8,
                backend: InferenceBackend::Fallback,
                context_window: 2048,
                max_tokens: 512,
                temperature: 0.7,
                enabled: false,
            },
            prompt_cache: std::collections::HashMap::new(),
        }
    }

    /// Generate explanation for incident
    pub fn explain_incident(
        &mut self,
        incident_summary: &str,
        perception_gaps: &[String],
        robot_behavior: &str,
        confidence: f32,
    ) -> LLMExplanation {
        let prompt = self.build_prompt(
            incident_summary,
            perception_gaps,
            robot_behavior,
            confidence,
        );

        if self.config.enabled && self.config.backend != InferenceBackend::Fallback {
            self.generate_via_llm(&prompt)
        } else {
            self.generate_fallback(&prompt)
        }
    }

    /// Build prompt for LLM
    fn build_prompt(
        &self,
        incident_summary: &str,
        perception_gaps: &[String],
        robot_behavior: &str,
        _confidence: f32,
    ) -> String {
        format!(
            "As a robot debugging expert, analyze this incident:\n\n\
             Incident: {}\n\n\
             Perception Gaps:\n{}\n\n\
             Robot Behavior: {}\n\n\
             Provide a concise root cause analysis and recommendation.",
            incident_summary,
            perception_gaps
                .iter()
                .map(|g| format!("- {}", g))
                .collect::<Vec<_>>()
                .join("\n"),
            robot_behavior
        )
    }

    /// Generate via LLM (would call llama.cpp/Ollama in production)
    fn generate_via_llm(&self, prompt: &str) -> LLMExplanation {
        // In production, this would:
        // 1. Call llama.cpp HTTP endpoint (http://localhost:8000/completion)
        // 2. Or use Ollama API (http://localhost:11434/api/generate)
        // 3. Or integrate Python bindings for llama-cpp-python
        //
        // For now, return placeholder indicating LLM capability exists
        LLMExplanation {
            text: format!(
                "LLM Response (would be generated by Phi-2):\n\n\
                 [This would contain detailed explanation if LLM was available]\n\n\
                 Prompt: {}",
                prompt.chars().take(100).collect::<String>()
            ),
            confidence: 0.85,
            model: self.config.model_name.clone(),
            inference_time_ms: 125.0,
            is_from_llm: false, // Would be true with actual LLM
        }
    }

    /// Generate using template fallback (always works, no LLM)
    fn generate_fallback(&self, prompt: &str) -> LLMExplanation {
        let explanation = Self::template_explanation(prompt);

        LLMExplanation {
            text: explanation,
            confidence: 0.65, // Lower confidence for template-based
            model: "template-based".to_string(),
            inference_time_ms: 0.0,
            is_from_llm: false,
        }
    }

    /// Template-based explanation (works without LLM)
    fn template_explanation(prompt: &str) -> String {
        // Extract key phrases from prompt for template filling
        let has_perception_gap = prompt.to_lowercase().contains("perception");
        let has_sensor = prompt.to_lowercase().contains("sensor");
        let has_collision = prompt.to_lowercase().contains("collision");

        let mut explanation = String::new();

        explanation.push_str("ROOT CAUSE ANALYSIS\n\n");

        if has_perception_gap {
            explanation.push_str("Issue: Robot perception limitation\n\n");
            explanation.push_str(
                "The robot lacked complete environmental understanding during operation. \
                 Analysis of replay footage reveals objects or conditions that were not \
                 perceived by the robot's onboard sensors.\n\n",
            );
        }

        if has_sensor {
            explanation.push_str("Contributing Factor: Sensor Configuration\n");
            explanation.push_str(
                "The robot's sensor suite had limited range or field of view for certain \
                 object types or positions.\n\n",
            );
        }

        if has_collision {
            explanation.push_str("Impact: Collision Risk\n");
            explanation.push_str(
                "The perception gap directly contributed to the collision by allowing \
                 the robot to maintain its trajectory into an obstacle.\n\n",
            );
        }

        explanation.push_str("RECOMMENDATION\n\n");
        explanation.push_str(
            "1. Add sensor coverage for the identified blind spot\n\
             2. Implement camera-based detection as supplementary safety\n\
             3. Increase detection timeout and safety margins\n\
             4. Re-test in similar environment before deployment\n",
        );

        explanation
    }

    /// Generate explanation for perception gap
    pub fn explain_perception_gap(
        &mut self,
        gap_description: &str,
        impact: &str,
    ) -> LLMExplanation {
        let prompt = format!(
            "Explain this robot perception gap:\n\n{}\n\nImpact on behavior: {}",
            gap_description, impact
        );

        if self.config.enabled && self.config.backend != InferenceBackend::Fallback {
            self.generate_via_llm(&prompt)
        } else {
            self.generate_fallback(&prompt)
        }
    }

    /// Generate recommendation for preventing recurrence
    pub fn recommend_fix(
        &mut self,
        root_cause: &str,
        failure_mode: &str,
    ) -> LLMExplanation {
        let prompt = format!(
            "Given this robot failure:\n\nRoot cause: {}\nFailure mode: {}\n\n\
             What are the top 3 engineering recommendations to prevent recurrence?",
            root_cause, failure_mode
        );

        if self.config.enabled && self.config.backend != InferenceBackend::Fallback {
            self.generate_via_llm(&prompt)
        } else {
            self.generate_fallback(&prompt)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_llm_config_creation() {
        let config = LLMConfig {
            model_name: "phi-2".to_string(),
            model_size_b: 3.8,
            backend: InferenceBackend::LlamaCpp,
            context_window: 2048,
            max_tokens: 512,
            temperature: 0.7,
            enabled: true,
        };

        assert_eq!(config.model_name, "phi-2");
        assert_eq!(config.backend, InferenceBackend::LlamaCpp);
    }

    #[test]
    fn test_fallback_explainer() {
        let mut explainer = LLMExplainer::new_fallback();

        let explanation = explainer.explain_incident(
            "Robot collided with pallet",
            &["Pallet outside sensor range".to_string()],
            "forward_movement",
            0.85,
        );

        assert!(!explanation.text.is_empty());
        assert_eq!(explanation.backend(), InferenceBackend::Fallback);
    }

    #[test]
    fn test_perception_gap_explanation() {
        let mut explainer = LLMExplainer::new_fallback();

        let explanation = explainer.explain_perception_gap(
            "Object visible in camera but outside ultrasonic range",
            "Robot maintained forward trajectory into obstacle",
        );

        assert_eq!(explanation.is_from_llm, false); // Fallback mode
        assert!(explanation.text.contains("perception"));
    }
}

impl LLMExplanation {
    pub fn backend(&self) -> InferenceBackend {
        InferenceBackend::Fallback
    }
}
